dist: xenial
language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
  - 'pypy3.5'
install:
  - pip install pytest
  - pip install .
script:
  - pytest
deploy:
  provider: pypi
  user: rurlus
  password:
    secure: otIvUbwtTCthtEjSOMC8QwLu1Hvm1ROpS/T+6sDbMT1es79UZGxQWMArl7bvVaSLbGdBNo9n6/lwxAuL6L5B2iATxVQiVlju2JVVggDcV2/Bz95xXfVNOiTKz/krUhptKSkQFyq+EWpvbfyVPiH1CKxVUlhdvR9dfg7QQKPqDrmKNF2wT9w5v52xuqlpu0ifvQpd8QOn0fwwW4bmxTjjaUJCMxkhfMYOg2Fr+HXk2uiA4YBApKj65KqhkB/ZN3ut1p39e5J9J+UveeDkr6KQCchnMCt6FR6wrLxX1n14/y4yhTPLNdnVcTDVAx/TI9DR+KnlnMTYdOxJptxIFyMcmzPNRBCLEt0H/n1vGJWnaUBMXLeMYhOakpxjZwQ/ANWBleavX2sHDHOydD6gS+SuZsZKPYcYpBZcDIpDbGlaM6+UDkkUkZiJT/bh3J+fjETJfY6j3cH875hKvd5XCLiqqN5VAo98W7hqtIw9ptEsUlb16AMbTqJBVcKrUCdAOLimL+LxilqylL9DRdEqGMmyHE2p4WjwPPc48d1S4iHcl6GwjJulNrb/po89BWwHa3C5UApI71i0b//ipkgN5NVHCPiioj2leD24HmCSNUutA0VY+z+JAzYbL+lBYbjZSCCb0qbPacmSG8gCgHwnf91KrUL+x4XZ9/4LV1g2ETiJrig=
  on:
    tags: true
