language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
# PyPy versions
  - "pypy3.5"
  - "pypy3.6"
  - "pypy3.7"
# command to install dependencies
install:
  - pip install .
# command to run tests
script:
  - pytest
