dist: xenial
language: python
python:
  - '2.7'
  - '3.5'
  - '3.6'
  - '3.7'
  - '3.8'
  - 'pypy3.5'
install:
  - pip install pytest
  - pip install .
script:
  - pytest
deploy:
  provider: pypi
  user: 'rurlus'
  password:
    secure: pI1KMW+FOuwRsMudAwC3L0FOGMFacSxwYBXPrK8rWT9roeBtN/Pwok2uwKFcTm8y/bX5fBdalheXkAb5bQkuMBwQfbgZWdV101hf1obiAuvVaDD1+eDeX3w53WaziocCR3xkWU9U/T/x20DXKtxJI1UI7hjx6BlklZhgcwgX4efMFpzrc2B8r2dwZqFAMKRsyhxR67pgonWwDAc5jaSAgSFr8iybE++Mxzw/pQQ4U0YnQ/sOXXnEegieTf+6Y0XOMimW1YnmDvCV6SWRA0vYzKDrGcgD/OzLMLdL6fT7uUt91C2ERdHIdmhfo3qxuMYYnORF2dFA9sxZ74lu99utu7UYskGmzthVtiv66BGGXm1bj7pY+GjsfZvX3M9lzTDKKkANwB1bBg7hR9n3kVZ0CfDnWh0cSXK+R4viC4QM5yiXfwbPxmwefovkFHd2PW9vueiAEp87YmcxrnpfZ+AlKrt3UOKaHJObah44Ci3cyyNky7KcpvWz9wA8vbNQALQF7GlNVm4jzjiv8B+DPX3QGHqUVJNr3EayEMwZC6fW25YLXoRHy89ZklTrp6n4jLvnGhgwlIz9twUfObQ2sG24XtrxNqZa8S3q7uNY32c0DfcH5MbMoACoL0VmgtLqcKodBXuTpnJz6K4SBpoyT8Odju9Eh2g9J+UK+3xE6dc7RZI=
  on:
    tags: true
  skip_existing: true
